---
# file: roles/fubarhouse.python/tasks/pyenv.yml

- name: "PyEnv | Check directory permissions"
  file:
    path: "{{ shell_home_dir.stdout }}/{{ pyenv_main_dir }}"
    state: directory
    mode: 0755
    recurse: yes
  failed_when: false
  changed_when: false

- name: "PyEnv | Cloning/Updating"
  git:
    repo: "{{ repo_pyenv }}"
    dest: "{{ shell_home_dir.stdout }}/{{ pyenv_main_dir }}"
    clone: yes
    update: no
    force: no
    recursive: false

- name: "PyEnv | Create symlink"
  file:
    src: "{{ shell_home_dir.stdout }}/{{ pyenv_main_dir }}/{{ pyenv_bin_path }}/{{ pyenv_main_exec }}"
    dest: "{{ pyenv_symlink_exec }}"
    mode: 0755
    state: link

- name: "PyEnv | Ensure shell profiles are available"
  file:
    path: "{{ shell_home_dir.stdout }}/{{ item.filename }}"
    state: touch
  with_items: "{{ shell_profiles }}"
  failed_when: false
  when: shell_profiles is defined

- name: "PyEnv | Ensure shell profiles are configured"
  lineinfile:
    dest: "{{ shell_home_dir.stdout }}/{{ item[0].filename }}"
    regexp: "{{ item[1].regex }}"
    line: "{{ item[1].lineinfile }}"
    state: present
  with_nested:
  - "{{ shell_profiles }}"
  - "{{ fubarhouse_python_shell_exports }}"
  ignore_errors: yes
  when:
    - shell_profiles is defined
    - fubarhouse_python_shell_exports is defined