---
# file: roles/fubarhouse.python/tasks/pypi.yml

#- name: "PyPI | Ensure absent"
#  pip:
#    name: "{{ item }}"
#    state: absent
#  with_items: "{{ python_packages }}"

- name: "PyPI | Ensure installed and updated"
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_packages }}"
