---
# file: roles/fubarhouse.python/tasks/python.yml

- name: "Python | Check python versions"
  shell: "{{ pyenv_symlink_exec }} versions"
  register: installed_python_versions
  changed_when: false

- name: "Python | Install Python"
  shell: "{{ pyenv_symlink_exec }} --debug install {{ item }}"
  with_items:
    - "{{ python_version }}"
    - "{{ python_versions }}"
  register: python_installation
  when: 'item not in installed_python_versions.stdout'

- name: "Python | Verify python versions"
  shell: "{{ pyenv_symlink_exec }} versions"
  register: newly_installed_python_versions
  changed_when: false