---

- name: "PyEnv | Get $HOME"
  shell: "echo $HOME"
  register: shell_home_dir
  changed_when: false
  when: shell_home_dir is not defined

- name: "PyEnv | Define shell exports"
  set_fact:
    fubarhouse_python_shell_exports:
    - lineinfile: 'export PYENV_ROOT="{{ shell_home_dir.stdout }}/{{ pyenv_main_dir }}"'
      regex: 'export PYENV_ROOT="{{ shell_home_dir.stdout }}/{{ pyenv_main_dir }}"'
    - lineinfile: 'export PATH="$PYENV_ROOT/bin:$PATH"'
      regex: '\$PYENV_ROOT/bin:\$PATH'
    - lineinfile: 'eval "$(pyenv init -)"'
      regex: 'pyenv init -'
  when: fubarhouse_python_shell_exports is undefined
