---

- name: "Installing dependencies"
  dnf:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - xz
    - xz-devel