---

- name: "Installing dependencies"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - readline
    - xz

- name: "PyPI | Ensure Installed"
  easy_install:
    name: pip
    state: latest
